# Generated by Django 2.1.1 on 2022-03-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='name',
            field=models.CharField(default='phrase', max_length=20),
        ),
    ]
