# Generated by Django 2.1.1 on 2022-03-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_phrase_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='name',
        ),
    ]
